const SETTINGS = {
    BOARD_COLS_WIDE: 10,
    BOARD_ROWS_HIGH: 18,
    PIECE_START_COL: 4,
    PIECE_START_ROW: 1,
    PIECE_START_POS: 1,
    GAME_INTERVAL_MS: 460,
    GAME_SCORE_MULTIPLIER: 100,
    CELL_WIDTH_PX: 20,
    CELL_HEIGHT_PX: 20
};

export { SETTINGS };
